# Generated by Django 3.1.7 on 2021-03-19 03:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_creation', models.DateTimeField(verbose_name='date created')),
                ('date_update', models.DateTimeField(default=datetime.datetime(2021, 3, 19, 3, 29, 34, 240077, tzinfo=utc), verbose_name='date updated')),
            ],
        ),
    ]
